# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    # env:
    #   ACRHOST: ${{ secrets.ACR_HOST }} 
    #   CSCCUID: ${{ secrets.CSCCUID }}
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
    
    - name: log into Azure CR
      uses: azure/docker-login@v1
      with:
        login-server: ewagner14cscc.azurecr.io
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: |
        # docker build . -t $ACRHOST:/week10-example:$CSCCUID-test1
        # docker push $ACRHOST:/week10-example:$CSCCUID-test1
        docker build . -t ${{ env.ACRHOST }}/week10-example:${{ env.CSCCUID }}-test1
        docker push ${{ env.ACRHOST }}/week10-example:${{ env.CSCCUID }}-test1
